options:
  auto-update: true
  # Should custom names be used to show resources
  display-resource-in-name: true
  # The max number of heterozygous genes a newly converted chicken can generate, from 1-6
  max-mutation: 2
  # The percent chance that a newly converted chicken will have any recessive alleles
  mutation-rate: 50
