name: GeneticChickengineering

author: kiichan

description: An addon for SlimeFun that adds resource chickens

main: space.kiichan.geneticchickengineering.GeneticChickengineering

website: https://github.com/kii-chan-reloaded/GeneticChickengineering

depend: [Slimefun]

version: ${project.version}

api-version: 1.16
