name: GeneticChickengineering

author: kiichan

description: 黏液科技附加 基因工程雞 繁體翻譯版.

main: space.kiichan.geneticchickengineering.GeneticChickengineering

website: https://github.com/kii-chan-reloaded/GeneticChickengineering

depend: [Slimefun]

version: ${project.version}

api-version: 1.16

commands:
    geneticchickengineering:
        aliases: gce
        description: GCE base command
        usage: "Usage: /<command> <subcommand> [arguments]"
permissions:
  geneticchickengineering.command.makechicken:
    description: Allows a player to make Pocket Chickens with commands
    default: op
  geneticchickengineering.command.calculatechance:
    description: Allows a player to calculate the chances of getting a specific offspring from two parents
    default: true
