name: GeneticChickengineering

author: kiichan

description: 黏液科技附加 基因工程雞 繁體翻譯版.

main: space.kiichan.geneticchickengineering.GeneticChickengineering

website: https://github.com/kii-chan-reloaded/GeneticChickengineering

depend: [Slimefun]

version: ${project.version}

api-version: 1.16
