name: Build Pull Request

on:
  push:

    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # jdk 设置
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package -T 2C
      - name: select jar
        run: |
          cd target
          rm -rf original*
          echo "FILE=$(ls | grep jar)" >> $GITHUB_ENV
      - name: Archive artifacts (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}
          path: target/${{ env.FILE }}