name: Build Pull Request

on:
  push:

    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # jdk 设置
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package -T 2C
      - name: select jar
        run: |
          cd target
          rm -rf original*
          echo "FILE=$(ls | grep jar)" >> $GITHUB_ENV
      - name: Archive artifacts (artifacts)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: ${{ env.FILE }}
          path: target/${{ env.FILE }}